// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7e0d319a09eca6c34035a0900757b60f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"56a843f683c28af8d3acb35582da637c": "1f8b08000000000000ff3ccd31aec2301084e17e4f314da4e415cf1700ae0015fd926c8885b1adf56e1121ee8e808876a4ff9bcae38daf825db747e6bbfc9fbe433fa03b10d95a05c76ab1e48666eaa3e1414008e069c25a5cd1cce7198ba8d0938842c099539cd804b6b0a16c39abc09bf32509cd9e47f4a55ac3dfc60fbfac1f20aa453f4f2ae69a91637aebaf000000ffff53d53da3af000000",
		"67c2b59c8741c3fe3f9db52e4e4a72ed": "1f8b08000000000000fff248cdc9c957482bcacf55b051b555c84bcc4dd50bc92cc949cdac4ad5d05450b5e302040000ffff122b7d2a22000000",
		"91ab460f060e204b86863ca1392680ef": "1f8b08000000000000ff74ce314ff33010c6f1d9f7291e45eaabf81d9cbda24cb0360c116b65926b6215c7e17c01a1aadf1d25442c88d5ffc73fdde4db8bef1977bb03461fd93d7d3f9416bb7ba210a7248a924ca19c358c7d41648a3ee830bfb836c52aabb0b683546b3f7f56c26f73102ec8129de7b145c3594ff5a4218df9f4ec5f43e7954bc5ff4d748dc5958c607fc0f6d91df9a3544b64d2a47909ff36e07a23c3b26e97e47e3c4b46dca3489292452c11505568ea877a8fe82f8ca0785fc60efb055e90df0620ee98fe607cd721a7c88849183e6796f5260c2cece8465f010000ffff742fed224d010000",
		"bb890f3a8aa56c497012afb45b9738ad": "1f8b08000000000000ff9c514d6be33010bdeb57cc0a02520832ec717793c316da5b5a4869cf8a3b56846dc98cc6ad4bc97f2f92fb410a6da1d7f7debc79336fb0756b1dc2bfc51a82edd15ccd80d2b0d808e1fb2112831200d2793e8c7b53c7be72713f368ded62e5308447f9293d74633a380c5f286cdd5275fffb1b8f8ff4d0ba0a89222529b410cd186ad8e2838a0327585e0eec63481ad4b204341718902c475a4199d2f024001cfc59c32cc8b35a0800df644526b295b9b19dbfb38c4aff2df8af3504df956900421e29807b314de6d6f361c7b66e15126901703cb574e67f9c5439b96c94f9edfb386d6d8fb0d8c8154863aab72ece7d37175131f643671993d43f0d0250f39443947fe6f56731304eacf4cc991db292f96ab92ac767dc996bb22135917a24f55ae70958f3a4b3f43d44f09d380af11c0000ffff807fabc25c020000",
		"be63988dd6aff95c2a1ff130f81faee9": "1f8b08000000000000ff548fc14a03311086cf9ba7080b9544966cbd8af522f524554ac18388a4eb6c1adc24dbc9045b4adf5d922ea2971cbef932ff3fa3eebeb4017e375b70af1da8970b1092cfee19b36e0c485cb0aa268864bda919ab6a636997b6aa0bae35619bfa5e0fa135e0fd31bfd9acff5b9110a8db615bb6f4c716619f2c42cd24637df21ddf40a48f157c0be2d75394da487e6215f2db059f7c550cc958651a0e5846195d3d8f64838fa7b36415aa555822061480985d4c3e8b53b5bc639dbc0714b2ccd4aba59d30c5fcfd9af93a79210b86584a6406310d14c5c57e022f10a27a08ce69ff191b3e977ff9a31d2036fc26dbfde58e09becddfb3b8dc273d881a0eda8d03283a50ddf05eadb4831c7d663f010000ffff4748513ba1010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("genny:genny:new", "../new/templates")
		b.SetResolver("-name-/-name-.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "bb890f3a8aa56c497012afb45b9738ad"})
		b.SetResolver("-name-/-name-_test.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "be63988dd6aff95c2a1ff130f81faee9"})
		b.SetResolver("-name-/options.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "56a843f683c28af8d3acb35582da637c"})
		b.SetResolver("-name-/options_test.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "91ab460f060e204b86863ca1392680ef"})
		b.SetResolver("-name-/templates/example.txt.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "67c2b59c8741c3fe3f9db52e4e4a72ed"})
	}()

	return nil
}()
