name: Tests
on: [push]
jobs:
  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Test
        run: |
          go mod tidy -v
          go test -race ./...
